-- 1)
/*
SELECT DISTINCT XUCS.CODIGO, DESIGNACAO, XOCORRENCIAS.ANO_LETIVO, INSCRITOS,  TIPO, TURNOS
FROM XUCS
JOIN XOCORRENCIAS
    ON XUCS.CODIGO = XOCORRENCIAS.CODIGO
JOIN XTIPOSAULA
    ON (XUCS.CODIGO = XTIPOSAULA.CODIGO
    AND XTIPOSAULA.ANO_LETIVO = XOCORRENCIAS.ANO_LETIVO)
WHERE XUCS.DESIGNACAO = 'Bases de Dados'
    AND XUCS.CURSO = 275;
/*    

*/

-- 2)
/*
SELECT TIPO, SUM(HORAS_TURNO * N_AULAS) 
FROM XTIPOSAULA 
    JOIN XUCS 
        ON XTIPOSAULA.CODIGO = XUCS.CODIGO
WHERE ANO_LETIVO = '2004/2005'
    AND XUCS.CURSO = 233
GROUP BY TIPO;
/*

*/

-- 3.a)
/*
SELECT DISTINCT XUCS.CODIGO, XUCS.DESIGNACAO
FROM XUCS
    JOIN XOCORRENCIAS 
        ON XOCORRENCIAS.CODIGO = XUCS.CODIGO
    JOIN XTIPOSAULA
        ON (XTIPOSAULA.CODIGO = XOCORRENCIAS.CODIGO 
            AND XTIPOSAULA.ANO_LETIVO = XOCORRENCIAS.ANO_LETIVO)
WHERE XOCORRENCIAS.ANO_LETIVO = '2003/2004'
    AND XTIPOSAULA.ID 
        NOT IN (SELECT XDSD.ID 
                FROM XDSD
                JOIN XTIPOSAULA 
                    ON XDSD.ID = XTIPOSAULA.ID
                    WHERE XTIPOSAULA.ANO_LETIVO = '2003/2004');*/
/*
SELECT COUNT(XUCS.CODIGO)
    FROM XUCS
    JOIN XOCORRENCIAS
        ON XOCORRENCIAS.CODIGO = XUCS.CODIGO
    JOIN XTIPOSAULA
        ON (XTIPOSAULA.CODIGO = XUCS.CODIGO
            AND XOCORRENCIAS.ANO_LETIVO = XTIPOSAULA.ANO_LETIVO)
    WHERE XOCORRENCIAS.ANO_LETIVO = '2003/2004' AND XTIPOSAULA.ID NOT IN (SELECT XDSD.ID
    FROM XUCS
    JOIN XOCORRENCIAS
        ON XOCORRENCIAS.CODIGO = XUCS.CODIGO
    JOIN XTIPOSAULA
        ON (XTIPOSAULA.CODIGO = XUCS.CODIGO
            AND XOCORRENCIAS.ANO_LETIVO = XTIPOSAULA.ANO_LETIVO)
    JOIN XDSD
        ON XTIPOSAULA.ID = XDSD.ID
    WHERE XOCORRENCIAS.ANO_LETIVO = '2003/2004');
-- 3.b)
*/

-- 4)
DROP VIEW DOC_AULA;
CREATE VIEW DOC_AULA AS
SELECT XDOCENTES.NR AS NR, XDOCENTES.NOME AS NOME, XTIPOSAULA.TIPO AS TIPO
    FROM XDOCENTES
        JOIN XDSD
            ON XDSD.NR = XDOCENTES.NR
        JOIN XTIPOSAULA
            ON XDSD.ID = XTIPOSAULA.ID
    WHERE XTIPOSAULA.ANO_LETIVO = '2003/2004'
    ORDER BY XDOCENTES.NR;

DROP VIEW AULA_ID_HORAS;
CREATE VIEW AULA_ID_HORAS AS
SELECT ID, NR AS DOC_NR, SUM(HORAS * FATOR) AS HORAS
    FROM XDSD
    GROUP BY ID, NR;

SELECT * FROM AULA_ID_HORAS;

DROP VIEW GROUPED_TIPO_DOC;
CREATE VIEW GROUPED_TIPO_DOC AS
SELECT NR AS DOC_NR, TIPO, SUM(HORAS) AS TOTAL_HORAS
    FROM DOC_AULA
    JOIN AULA_ID_HORAS
        ON DOC_AULA.NR = AULA_ID_HORAS.DOC_NR
    GROUP BY NR, TIPO;

DROP VIEW MAX_HORAS;
CREATE VIEW MAX_HORAS AS
SELECT TIPO, MAX(TOTAL_HORAS) AS MAX_HORAS
    FROM GROUPED_TIPO_DOC
    GROUP BY TIPO;

DROP VIEW FATOR_AULA;
CREATE VIEW FATOR_AULA AS
SELECT AULA_ID_HORAS.*, XDSD.FATOR, TIPO
    FROM AULA_ID_HORAS
        JOIN XDSD
            ON XDSD.NR = AULA_ID_HORAS.DOC_NR
            AND XDSD.ID = AULA_ID_HORAS.ID
        JOIN XTIPOSAULA
            ON XTIPOSAULA.ID = AULA_ID_HORAS.ID;

SELECT NR, XDOCENTES.NOME, MAX_HORAS.TIPO, MAX_HORAS --* FATOR
   FROM GROUPED_TIPO_DOC
        JOIN MAX_HORAS
            ON (GROUPED_TIPO_DOC.TIPO = MAX_HORAS.TIPO
                AND GROUPED_TIPO_DOC.TOTAL_HORAS = MAX_HORAS.MAX_HORAS)
        JOIN XDOCENTES
            ON GROUPED_TIPO_DOC.DOC_NR = XDOCENTES.NR;